export const RequestType = {
  LIVRAISON: 'LIVRAISON',
  REPRISE: 'REPRISE',
  DEPANNAGE: 'DEPANNAGE',
};

export const RequestStatus = {
  EN_ATTENTE: 'EN ATTENTE',
  PRISE_EN_COMPTE: 'PRISE EN COMPTE',
  EN_COURS_DE_REALISATION: 'EN COURS DE REALISATION',
  TERMINEE: 'TERMINEE',
};
